<a href="https://colab.research.google.com/github/ShohruhShokulov/mohirdev_datascience_AI/blob/main/Indexing_and_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr1 = np.arange(0,6).reshape(2,3)
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr1.size
arr1.shape

(2, 3)

In [ ]:
arr1.ndim

2

In [ ]:
float_arr1 = arr1.astype(np.int8)
float_arr1

array([[0, 1, 2],
       [3, 4, 5]], dtype=int8)

#Array slicing and indexing

In [ ]:
arr = np.array((1,2,3,4,5))
arr[0]

1

In [ ]:
arr[-1]

5

In [ ]:
print(arr[1]+arr[-1])

7


In [ ]:
arr[1:-1]

array([2, 3, 4])

In [ ]:
arr2= np.arange(0,101,10)
arr2

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
sliced_array = arr2[4:6]
sliced_array

array([40, 50])

In [ ]:
sliced_array[:]= 0  # " : " this sign means that all element of the array
sliced_array

array([0, 0])

In [ ]:
arr2  # so from the result below we may convince that when we change the slice of an array those elements inside an array will also change

array([  0,  10,  20,  30,   0,   0,  60,  70,  80,  90, 100])

In [ ]:
arr2[::2] # it prints every other element from an array

array([  0,  20,   0,  60,  80, 100])

#copy method

In [ ]:
sarr = arr2[4:6].copy()
sarr[:]= -1
arr2  # so with using the copy method we can prevent the change of the element

array([  0,  10,  20,  30,   0,   0,  60,  70,  80,  90, 100])

#Indexing 2D arrays

In [ ]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr1[1,2] #it should output 5 because it finds 2nd element form 2nd raw

5

In [ ]:
arr1[0,1:] # from 1st raw slice all elements from 1

array([1, 2])

In [ ]:
arr1[1,0:3]

array([3, 4, 5])

In [ ]:
arr1[0:2,2] # from  the raws from number 1 to 3, slice 2nd element

array([2, 5])

In [ ]:
arr1[1,[0,2]]

array([3, 5])

In [ ]:
arr1[0:2,0:2]

array([[0, 1],
       [3, 4]])

#Indexing and slicing 3D array

In [ ]:
arr3 = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
arr3[0]

array([[1, 2, 3]])

In [ ]:
arr3[1,0,2]

6

In [ ]:
arr3[2][0,2]

9

In [ ]:
arr3[1][0][0]

4

In [ ]:
import numpy as np
array1 = np.arange(0,10).reshape(2,5)
array1.astype(np.float128)
array1.dtype

dtype('int64')

#Boolean inexing

In [ ]:
names = np.array(["shohruh","mirsiad","miron","elbek","shohruh"])
names

array(['shohruh', 'mirsiad', 'miron', 'elbek', 'shohruh'], dtype='<U7')

In [ ]:
data = np.random.randn(5,4)
data

array([[-1.42508694, -0.0854746 ,  0.3099696 ,  0.34419037],
       [ 0.53379708,  0.05661724, -1.36098466,  0.66815246],
       [-0.46621192,  0.71966811,  0.54056005,  1.88096599],
       [-0.53682587,  0.19271711,  0.4965673 , -0.58622886],
       [-2.13394203,  1.30770222, -0.14275349,  0.49299426]])

In [ ]:
names == "shohruh"

array([ True, False, False, False,  True])

In [ ]:
data[names == "shohruh"] # slice the information related to "shohruh"

array([[-1.42508694, -0.0854746 ,  0.3099696 ,  0.34419037],
       [-2.13394203,  1.30770222, -0.14275349,  0.49299426]])

In [ ]:
data[names == "shohruh"][1,2:4]

array([-0.14275349,  0.49299426])

In [ ]:
data[names == "shohruh"][1,[2,3]]

array([-0.14275349,  0.49299426])

In [ ]:
data[names == "shohruh",2:]

array([[ 0.3099696 ,  0.34419037],
       [-0.14275349,  0.49299426]])

In [ ]:
data[names !="shohruh"] # slice the information of all except "shohruh"

array([[ 0.53379708,  0.05661724, -1.36098466,  0.66815246],
       [-0.46621192,  0.71966811,  0.54056005,  1.88096599],
       [-0.53682587,  0.19271711,  0.4965673 , -0.58622886]])

In [ ]:
data[~(names == "shohruh")]

array([[ 0.53379708,  0.05661724, -1.36098466,  0.66815246],
       [-0.46621192,  0.71966811,  0.54056005,  1.88096599],
       [-0.53682587,  0.19271711,  0.4965673 , -0.58622886]])

In [ ]:
print(names)
print(data)

['shohruh' 'mirsiad' 'miron' 'elbek' 'shohruh']
[[-1.42508694 -0.0854746   0.3099696   0.34419037]
 [ 0.53379708  0.05661724 -1.36098466  0.66815246]
 [-0.46621192  0.71966811  0.54056005  1.88096599]
 [-0.53682587  0.19271711  0.4965673  -0.58622886]
 [-2.13394203  1.30770222 -0.14275349  0.49299426]]


In [ ]:
data[(names == "shohruh") | (names == "miron")] # slices the information of miron and shohruh

array([[-1.42508694, -0.0854746 ,  0.3099696 ,  0.34419037],
       [-0.46621192,  0.71966811,  0.54056005,  1.88096599],
       [-2.13394203,  1.30770222, -0.14275349,  0.49299426]])

In [ ]:
mask = (names == "shohruh")|(names == "miron")
mask

array([ True, False,  True, False,  True])

In [ ]:
data[data<0]= 0

In [ ]:
data

array([[0.        , 0.        , 0.3099696 , 0.34419037],
       [0.53379708, 0.05661724, 0.        , 0.66815246],
       [0.        , 0.71966811, 0.54056005, 1.88096599],
       [0.        , 0.19271711, 0.4965673 , 0.        ],
       [0.        , 1.30770222, 0.        , 0.49299426]])