<a href="https://colab.research.google.com/github/ShohruhShokulov/mohirdev_datascience_AI/blob/main/mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [ ]:
import numpy as np
np.__version__

'1.25.2'

In [ ]:
np.show_config

<function numpy.__config__.show()>

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [ ]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
arr1 = np.array([1,2,3,4,5,6])
arr1.size # size of an array

6

In [ ]:
arr1.itemsize # how much memory it is taking in the memory of the computer

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
vector = np.zeros(12)
vector[5] = 1
vector

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
vector = np.arange(20,60)
vector

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
vector[::-1]

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
np.arange(12,21).reshape(3,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
array = [3,7,0,0,9,0]
np.nonzero(array)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.






`💡Ishora` np.random.random

In [ ]:
np.random.random(8).reshape(2,2,2)

array([[[0.01781776, 0.95288789],
        [0.31633408, 0.37580172]],

       [[0.78895148, 0.61247305],
        [0.53568397, 0.03498366]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
array1 = np.random.randn(9,9)
array1.min()

-2.820748041566695

In [ ]:
np.max(array1)

(9, 9)

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
x = np.arange(18).reshape(6,3)
y = np.arange(3,15).reshape(3,4)
x.dot(y)

array([[ 29,  32,  35,  38],
       [ 92, 104, 116, 128],
       [155, 176, 197, 218],
       [218, 248, 278, 308],
       [281, 320, 359, 398],
       [344, 392, 440, 488]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [6]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-57-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-57-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-57-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping

---




`💡Ishora` np.intersect1d

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
b = np.array([3,6,7,8,9,10])
np.intersect1d(a,b)

array([3, 6, 7])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

*italicised text*`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
array = np.array([1.2,3.4,5,6.7,8.99])
array

array([1.2 , 3.4 , 5.  , 6.7 , 8.99])

In [ ]:
# first method "astype" method
array.astype(np.int32)

array([1, 3, 5, 6, 8], dtype=int32)

In [ ]:
# second method "np.floor"
np.floor(array)

array([1., 3., 5., 6., 8.])

In [ ]:
#third method "np.trunc"
np.trunc(array)

array([1., 3., 5., 6., 8.])

In [ ]:
# forth method "%"
int_part = array - (array%1)
int_part

array([1., 3., 5., 6., 8.])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
row_values = np.arange(3)
matrix = np.tile(row_values, (3, 1))
matrix

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [8]:
x = np.random.randn(10)
x

array([-0.09573399, -0.512407  ,  0.68226533, -0.3445028 ,  0.66637119,
       -0.4687482 , -2.01750548,  1.36416597,  0.28888681,  0.88548773])

In [10]:
# sorting an array using sort function
np.sort(x)

array([-2.01750548, -0.512407  , -0.4687482 , -0.3445028 , -0.09573399,
        0.28888681,  0.66637119,  0.68226533,  0.88548773,  1.36416597])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [ ]:
arr1 = np.random.randn(3,2)
arr2 = np.random.randn(3,2)
np.allclose(arr1,arr2)

False

In [ ]:
np.array_equal(arr1,arr2)

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [ ]:
x = np.arange(0,18).reshape(6,3)
y = np.arange(3,15).reshape(3,4)
x


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
y

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [ ]:
# multiplication of two matrices x and y
np.dot(x,y)

array([[ 29,  32,  35,  38],
       [ 92, 104, 116, 128],
       [155, 176, 197, 218],
       [218, 248, 278, 308],
       [281, 320, 359, 398],
       [344, 392, 440, 488]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [ ]:
array2 = np.random.randn(5)
array2

array([-0.65678008,  1.01842258, -0.03052492, -2.01718946,  1.67403201])

In [ ]:
max_index = np.argmax(array2) # argmax function is used to find the index of maximum value in an array
array2[max_index]= 0

In [ ]:
array2

array([-0.65678008,  1.01842258, -0.03052492, -2.01718946,  0.        ])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
today = np.datetime64("today","D") # today's date
today

numpy.datetime64('2024-03-04')

In [ ]:
yesterday= today - np.timedelta64(1,"D") # yesterday's date
yesterday

numpy.datetime64('2024-03-03')

In [ ]:
# tommmorows date
tommorow = today + np.timedelta64(1,"D")
tommorow

numpy.datetime64('2024-03-05')

#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
dates_jan_2016 = np.arange('2016-01-01', '2016-02-01', dtype='datetime64[D]')
dates_jan_2016

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:
array = np.array([1.2,3.4,5,6.7,8.99])
array

array([1.2 , 3.4 , 5.  , 6.7 , 8.99])

In [ ]:
# first method "astype" method
array.astype(np.int32)

array([1, 3, 5, 6, 8], dtype=int32)

In [ ]:
np.floor(array)

array([1., 3., 5., 6., 8.])

In [ ]:
np.trunc(array)

array([1., 3., 5., 6., 8.])

In [ ]:
array - array%1

array([1., 3., 5., 6., 8.])

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [ ]:
a = np.array([1,2,3,4,5])
np.add.reduce(a)

15

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [1]:
import numpy as np
ar1 = np.array([1,2,3,4,5])
ar2= [x for num in ar1 for x in (num, 0, 0, 0)]
ar2

[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [2]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
b = [a[i:i+4] for i in range(len(a)-3)]
b

[[1, 2, 3, 4],
 [2, 3, 4, 5],
 [3, 4, 5, 6],
 [4, 5, 6, 7],
 [5, 6, 7, 8],
 [6, 7, 8, 9],
 [7, 8, 9, 10],
 [8, 9, 10, 11],
 [9, 10, 11, 12],
 [10, 11, 12, 13],
 [11, 12, 13, 14]]

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [5]:
array = np.array([1,1,2,3,5,4,4,5,7,8,5,2,3,0])
np.bincount(array)

array([1, 2, 2, 2, 2, 3, 0, 1, 1])

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`