<a href="https://colab.research.google.com/github/ShohruhShokulov/mohirdev_datascience_AI/blob/main/numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
- Numpy array


In [ ]:
import numpy as np

my_list = list(range(10000)) #list created in pyhton
my_array = np.array([range(10000)])  # an array created using numpy array


In [ ]:
%time for _ in range(10): [x*2 for x in my_list]


CPU times: user 7.74 ms, sys: 0 ns, total: 7.74 ms
Wall time: 8.26 ms


In [ ]:
%time for _ in range(10): my_array*2

CPU times: user 1.35 ms, sys: 0 ns, total: 1.35 ms
Wall time: 1.44 ms


In [ ]:
data1 = [1,2 ,3,4] #list
arr1 = np.array(data1) #numpy Array

In [ ]:
data1

[1, 2, 3, 4]

In [ ]:
arr1

array([1, 2, 3, 4])

In [ ]:
data2 = (1,2,3,4) #tuple
arr2 = np.array(data2) # Array

In [ ]:
data2

(1, 2, 3, 4)

In [ ]:
arr2

array([1, 2, 3, 4])

#size of array

In [ ]:
arr1.ndim #size of array 1

1

In [ ]:
arr2.ndim #size of array 2

1

In [ ]:
data3 = [[1,2,3,4],[5,6,7,8]] # nested list
arr3 = np.array(data3) # array3

In [ ]:
data3

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr3.ndim

2

#Shape and size methods in array
- shape method is used to showing the number of raws and colums. Return tuple (r,  c)
- size methods is used to showing the number of elements in an array

In [ ]:
arr3.shape

(2, 4)

In [ ]:
arr3.size

8

# Creating numpy arrays using zeros and ones method

In [ ]:
arr4 = np.zeros(shape=(2,4))


In [ ]:
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr5 = np.ones(shape=(3,4))


In [ ]:
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#creating arrays using arrange method

In [ ]:
arr6 = np.arange(0,100,12) # arrange function is the same as the range function in pyhton


In [ ]:
arr6

array([ 0, 12, 24, 36, 48, 60, 72, 84, 96])