In [1]:
import numpy as np


In [3]:
a = np.array([1,2,3,4],ndmin=5)
a

array([[[[[1, 2, 3, 4]]]]])

In [10]:
arr1 = np.arange (0,100,10).reshape(2,5)
arr1

array([[ 0, 10, 20, 30, 40],
       [50, 60, 70, 80, 90]])

# Data types

In [12]:
arr1 = np.array([True,False])
arr1.dtype

dtype('bool')

In [13]:
arr2 = np.array([1,2,3,4,5],dtype = np.float64)
arr2

array([1., 2., 3., 4., 5.])

In [15]:
arr3 = np.array((1,2,3,4),dtype = np.int8)
arr3

array([1, 2, 3, 4], dtype=int8)

# astype method


In [16]:
array = np.array((1,2,3,4,5))
array.dtype


dtype('int64')

In [18]:
#int to float
float_array = array.astype(np.float64)
float_array

array([1., 2., 3., 4., 5.])

In [19]:
arr4 = np.array((1.2,1.4,2.3,5.6))
arr4.dtype

dtype('float64')

In [20]:
#float to integer

int_array = arr4.astype(np.int64)
int_array

array([1, 1, 2, 5])