<a href="https://colab.research.google.com/github/ShohruhShokulov/mohirdev_datascience_AI/blob/main/numpyday5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr1.ndim

2

In [4]:
arr1.size

9

In [6]:
arr1[2,1]

8

In [9]:
arr2 = np.array(["shohruh","miron","mirsaid"])
arr2

array(['shohruh', 'miron', 'mirsaid'], dtype='<U7')

In [10]:
arr1[arr2 == "shohruh"]

array([[1, 2, 3]])

#Transposing and Swapping

In [12]:
a = np.arange(0,6).reshape(3,2) #reshape method which is used to makiing the array like matrix
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [13]:
#transpose method
a.T # ".T " with using this method we can transpose our a array

array([[0, 2, 4],
       [1, 3, 5]])

In [19]:
#swapping axes
a.swapaxes(0,1)

array([[0, 2, 4],
       [1, 3, 5]])

In [21]:
#AAT
np.dot(a,a.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

#Universal functions
#unary function

In [28]:
array = np.arange(10).reshape(5,2)
array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
np.sqrt(array) # this function returns the square root of the numbers inside an array

array([[0.        , 1.        ],
       [1.41421356, 1.73205081],
       [2.        , 2.23606798],
       [2.44948974, 2.64575131],
       [2.82842712, 3.        ]])

In [30]:
np.square(array) # "square" function returns the square of an array

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [31]:
np.exp(array)

array([[1.00000000e+00, 2.71828183e+00],
       [7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03]])

In [33]:
np.log(array[1:]) # except first element all elements are log in the base of 2

array([[0.69314718, 1.09861229],
       [1.38629436, 1.60943791],
       [1.79175947, 1.94591015],
       [2.07944154, 2.19722458]])

#modf function which return the integer and residual parts

In [34]:
array1 = np.random.randn(6)
array1

array([ 1.00116806, -0.75478385,  0.193675  ,  0.05738448,  1.58715375,
       -0.7552189 ])

In [36]:
np.modf(array1)

(array([ 0.00116806, -0.75478385,  0.193675  ,  0.05738448,  0.58715375,
        -0.7552189 ]),
 array([ 1., -0.,  0.,  0.,  1., -0.]))

In [38]:
array2 = np.arange(-9,-1)
array2

array([-9, -8, -7, -6, -5, -4, -3, -2])

In [40]:
np.sign(array2) # "sign" function return 1 if number in array is positive, else returns -1 as shown below

array([-1, -1, -1, -1, -1, -1, -1, -1])

In [41]:
#isnan function
array1

array([ 1.00116806, -0.75478385,  0.193675  ,  0.05738448,  1.58715375,
       -0.7552189 ])

In [43]:
np.isnan(array1)

array([False, False, False, False, False, False])

In [46]:
array1[0]= np.NaN
array1

array([        nan, -0.75478385,  0.193675  ,  0.05738448,  1.58715375,
       -0.7552189 ])

In [45]:
np.isnan(array1)

array([ True, False, False, False, False, False])

In [50]:
ar1 = np.copy(array[1,1])
ar1

array(3)

#Binary functions
-  add, multiply, maximum

In [51]:
ar2 = np.random.randn(6)
ar3 = np.random.randn(6)


In [52]:
ar2

array([-0.24943853,  0.60524503,  0.17710495, -0.4356709 , -0.69725207,
       -0.92771875])

In [53]:
ar3

array([ 0.11820149, -0.97720283,  0.13572202, -0.17131498,  0.04324593,
        0.61489762])

In [54]:
#add function
np.add (ar2,ar3)

array([-0.13123704, -0.37195779,  0.31282697, -0.60698587, -0.65400614,
       -0.31282113])

In [60]:
# multiply function
np.multiply(ar1,ar2)

array([-0.74831559,  1.8157351 ,  0.53131485, -1.30701269, -2.09175621,
       -2.78315626])

In [61]:
a = np.array([1,2])
b = np.array([3,4])
np.maximum(a,b)

array([3, 4])

#where Mantiqiy shart operatori
-   if condtion is true, element from the first array in the posion of the contion operator will be called. Else if it is false, elemnets from the second array will be called

In [62]:
x = np.array([1.1,1.2,1.3,1.4,1.5])
y = np.array([2.1,2.2,2.3,2.4,2.5])


In [63]:
#conditions
cond = np.array([True,False,True,True,False])


In [64]:
np.where(cond,x,y)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [65]:
arr4 = np.random.randn(4)
arr4

array([ 0.57386245,  0.6566829 ,  0.01219263, -0.14498905])

In [66]:
np.where(arr4<0,-2,2) #if the element inside an array is negative, this function will return -2, else 2

array([ 2,  2,  2, -2])

In [69]:
a1 = np.arange(6).reshape(3,2)
a2 = np.arange(6,12).reshape(3,2)

In [71]:
a1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [72]:
a2

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [70]:
#add
a1+a2

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [73]:
#multiply
a1*a2

array([[ 0,  7],
       [16, 27],
       [40, 55]])

In [74]:
#subtract
a1-a2

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

In [75]:
# devide
a1/a2

array([[0.        , 0.14285714],
       [0.25      , 0.33333333],
       [0.4       , 0.45454545]])

In [76]:
#square
a1**2

array([[ 0,  1],
       [ 4,  9],
       [16, 25]])

In [77]:
ar1**0.5

1.7320508075688772