<a href="https://colab.research.google.com/github/ShohruhShokulov/mohirdev_datascience_AI/blob/main/numpyday6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])
con = np.array([True,True,False,True,False])

In [6]:
np.where(con,a,b)

array([ 1,  2, 30,  4, 50])

#Mathematic and Statistic methods and their usage

In [8]:
array = np.random.randn(5,4)
array

array([[ 0.06547503, -1.41651042,  0.19080865, -1.72282069],
       [ 0.10283822, -0.59296271,  0.79903305,  1.08487796],
       [ 1.79844809, -2.00457791,  1.28355016,  1.92997766],
       [-0.5444145 ,  0.13541963, -0.94300604,  1.24097162],
       [ 0.17255028,  0.6563819 ,  0.47840455, -0.87840983]])

In [9]:
# sum method which returns sum of the elements of an array
array.sum()

1.8360346931273375

In [10]:
np.sum(array)

1.8360346931273375

In [11]:
np.sum(array[0])

-2.8830474426687283

In [13]:
array.sum(axis = 1) # sum of raws

array([-2.88304744,  1.39378652,  3.007398  , -0.11102929,  0.4289269 ])

In [15]:
array.sum(axis = 0) # sum of colums

array([ 1.59489711, -3.22224951,  1.80879038,  1.65459671])

In [16]:
# mean method
data = np.arange(6)
data

array([0, 1, 2, 3, 4, 5])

In [19]:
mean = data.sum()/len(data)
mean

2.5

In [18]:
# mean method in numpy
np.mean(data)

2.5

In [20]:
array

array([[ 0.06547503, -1.41651042,  0.19080865, -1.72282069],
       [ 0.10283822, -0.59296271,  0.79903305,  1.08487796],
       [ 1.79844809, -2.00457791,  1.28355016,  1.92997766],
       [-0.5444145 ,  0.13541963, -0.94300604,  1.24097162],
       [ 0.17255028,  0.6563819 ,  0.47840455, -0.87840983]])

In [21]:
np.mean(array)

0.09180173465636687

In [22]:
array.sum()/array.size

0.09180173465636687

In [23]:
np.sum(array,axis = 1) # mean of raws of an array

array([-2.88304744,  1.39378652,  3.007398  , -0.11102929,  0.4289269 ])

In [24]:
np.sum(array,axis = 0) # mean of colums of an array

array([ 1.59489711, -3.22224951,  1.80879038,  1.65459671])

In [25]:
# cumsum method
data

array([0, 1, 2, 3, 4, 5])

In [26]:
data.cumsum()

array([ 0,  1,  3,  6, 10, 15])

# Numpy Sorting

In [28]:
arr = np.random.rand(4) # rand function returns random numbers between 0 and 1
arr

array([0.53743935, 0.50345105, 0.04476995, 0.79381227])

In [30]:
# sort function
arr.sort()
arr

array([0.04476995, 0.50345105, 0.53743935, 0.79381227])

In [31]:
sorted_arr = np.sort(arr)
sorted_arr

array([0.04476995, 0.50345105, 0.53743935, 0.79381227])

In [36]:
#reverse sorting
-np.sort(-arr)

array([0.79381227, 0.53743935, 0.50345105, 0.04476995])

In [37]:
# 2d array
arr2 = np.random.randn(2,4)
arr2

array([[-1.04949116, -0.55972945, -0.37490533, -1.07664935],
       [ 0.38319087,  0.97253636, -0.70585618, -0.14422135]])

In [38]:
# sorting by raw
np.sort(arr2,axis = 1)

array([[-1.07664935, -1.04949116, -0.55972945, -0.37490533],
       [-0.70585618, -0.14422135,  0.38319087,  0.97253636]])

In [39]:
# sorting by column
np.sort(arr2,axis = 0)

array([[-1.04949116, -0.55972945, -0.70585618, -1.07664935],
       [ 0.38319087,  0.97253636, -0.37490533, -0.14422135]])

In [40]:
# unique method
names = np.array(["shohruh","mirsaid","sarvar","miron","shohruh","sarvar"])
ints = np.array([2,2,2,3,3,3,1,1,4,4])

In [42]:
np.unique(names) # unique method will return unique items in an array in sorted order

array(['miron', 'mirsaid', 'sarvar', 'shohruh'], dtype='<U7')

In [45]:
# in1d method
ar1 = np.array([1,2,3,4,5,6])
ar2 = np.array([0,1,2,3])


In [46]:
np.in1d(ar1,ar2) # in1d function returns true if the element of array 1 in array2, else false

array([ True,  True,  True, False, False, False])

In [49]:
# setdiff1d method
names1 = np.array(["shohruh","miron","mirsaid","doston","elbek"])
names2 = np.array(["shohruh","miron","mirsaid"])


In [50]:
np.setdiff1d(names1,names2) # setdiff1d function returns elements in names1 which are not in names2

array(['doston', 'elbek'], dtype='<U7')

# Working with files in numpy

In [51]:
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.save("data",array1)

In [54]:
arr2 = np.load("data.npy")
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.savez("arrays",a = array1,b = arr2)

In [56]:
arrays = np.load("arrays.npz")

In [57]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arrays["b"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.savez_compressed('arrays_comp',a = array1, b = arr2)

# linier algebra
-   matrices

In [60]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
y = np.array([[7,8,9],[1,2,3]])
y

array([[7, 8, 9],
       [1, 2, 3]])

In [63]:
# adding
x + y

array([[ 8, 10, 12],
       [ 5,  7,  9]])

In [64]:
# subtracting
y-x

array([[ 6,  6,  6],
       [-3, -3, -3]])

In [65]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
y = np.array([[1,2],[4,5],[8,0]])
y

array([[1, 2],
       [4, 5],
       [8, 0]])

In [67]:
#multiplying
x.dot(y)

array([[33, 12],
       [72, 33]])

In [68]:
np.dot(x,y)

array([[33, 12],
       [72, 33]])

In [69]:
np.dot(y,x)

array([[ 9, 12, 15],
       [24, 33, 42],
       [ 8, 16, 24]])

In [72]:
a = np.arange(0,10,2)
a+1

array([1, 3, 5, 7, 9])